name: Feature request
description: Suggest a new feature
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      placeholder: What user problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      placeholder: Proposed behavior
    validations:
      required: true
